export const ANSWERS: string[] = [
	"I don't think so",
	"Things are looking up",
	"Search your own feelings",
	"Without a doubt",
	"Better not tell you now",
	"Thumbs Up",
	"It is certain",
	"Most likely",
	"In short, no",
	"Signs point to yes",
	"Ask again later",
	"My sources say no",
	"Yes",
	"Ask again",
	"Unlikely",
	"If you put the effort in",
	"I have my doubts",
	"By all means",
	"How am I supposed to know",
	"Thumbs down",
	"I can't tell at this time",
	"Things are looking up",
	"Why not",
	"Ask me in a year",
	"Yes",
	"Nope",
	"Totally",
	"Negative",
	"Out of the question",
	"Obviously",
	"I guess",
	"Not in your lifetime",
	"Without fail",
	"Thumbs up",
	"Not in a million years",
	"Try your luck"
];